### ISSUE TITLE
Create status page for our IT services

### ISSUE THREAD

**Issue by kelson42** [kiwix/container-images#192]
This is necessary to communicate more transparently about our IT servercives.

This is doable with uptime robot but we will have to pay.

https://github.com/louislam/uptime-kuma seems to be an interesting self-hosted alternative.

**Comment by kelson42** [comment]
https://console.dev/website-monitoring/

**Comment by kelson42** [comment]
@rgaudin @benoit74 Should we consider that this issue has been implemented with https://status.kiwix.org/ ?

**Comment by rgaudin** [comment]
Only you can answer this question I think
