### ISSUE TITLE
library.kiwix.org staging

### ISSUE THREAD

**Issue by kelson42** [kiwix/container-images#203]
We need a staging as library.kiwix.org becomes more critical.

**Comment by kelson42** [comment]
@rgaudin This ticket is really old and I don't remember the exact context. Does or could dev.library.kiwix.org plays this role?

**Comment by rgaudin** [comment]
I remember arguing that dev is no staging: different catalog, different software, different constraints.

I don't recall how this ticket was created but in the month leading to this, there had been numerous under-a-minute 503 alerts on uptime robot. Please note that this was prior to k8s and out varnish cache.

I suggest we close this. There's no info in this ticket and I'm sure this will come back in the future.
