### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by kelson42** [kiwix/container-images#226]
Historicaly this repository hosted scripts and solution for operations.

Since we have move to Docker only, years ago already, this host (almost) only Docker image code.

Therefore I propose to rename this repository to `kiwix/docker` and it would be the CI part of the `kiwix/k8s`

**Comment by rgaudin** [comment]
Agrees the name is not appropriate anymore. I don't think we can find a name that is both short and descriptive (`infra-docker-images`) so a shortcut like `images` or `docker` is fine.
We should make sure to describe what this is on the readme so visitors don't confuse this with docker images for our tools.

**Comment by kelson42** [comment]
Plan to go with `container-images`
