### ISSUE TITLE
Magnet links not working

### ISSUE THREAD

**Issue by rgaudin** [kiwix/container-images#242]
Mirrorbrain generated magnets are incorrect.

According to [the spec](https://en.wikipedia.org/wiki/Magnet_URI_scheme), here are the issues:

- encoding:
  - `&amp;` strings should be `&`
  - `as=` should be urlencoded
  - `tr=` should be urlencoded
- Webseed should be declared with `ws=`. `as=` is a _fallback_, not a webseed.
- Ideally we should have one `ws=` for each mirror.
- Missing `xs=`. This should be a link to the torrent file. Without it the webseed is useless as the magnet doesn't contain the torrent metadata and would thus wait forever to retrieve the metadata from a peer which has it (might happen if another BT user is seeding using a .torrent file… but unlikely). #43 would help of course.

This is upstream ; probably invalidated by #239

**Comment by kelson42** [comment]
Which part of this ticket has not been fixed/workarounded with https://github.com/kiwix/libkiwix/pull/1001?

**Comment by rgaudin** [comment]
None
