### ISSUE TITLE
Surfer doesn't build anymore

### ISSUE THREAD

**Issue by rgaudin** [kiwix/container-images#243]
See https://github.com/kiwix/container-images/actions/runs/5621647983/job/15232827787

Haven't checked but probably a dependency issue. We're just doing an `npm install` AFAIK

**Comment by benoit74** [comment]
I had a look into this issue. 

The fact that the build failed is linked to some files which are not present anymore in the release .tar.gz archive we download.

The underlying root problem is that Surfer has changed quite significantly and broke a significant part of our custom image.

From the changelog: 
```

[5.18.0]
* Move to vitejs as the buildtool
* Use nodejs 18.12.1

[6.0.0]
* Move from LDAP auth to Cloudron OpenID
* surfer cli now only works with API access tokens created in the admin UI
* WebDAV access requires an API access token as the password
```

Looks like there is no more admin CLI + there are probably other gotchas (e.g. I'm not sure that `.users.json` file is still in use).

Anyway, this means it is not a small issue solvable quickly, I stop to work on this for now until it gets prioritized

**Comment by kelson42** [comment]
@rgaudin Should we close this (now that we don'use Surfer for our drives)? Maybe there is a bit of cleaning work to do here as well?

**Comment by rgaudin** [comment]
i want to delete it from repo first
