### ISSUE TITLE
Update MirrorBrain base image

### ISSUE THREAD

**Issue by benoit74** [kiwix/container-images#244]
MirrorBrain image is currently based on `httpd:2.4.43` which is more or less 3 years old.

This means that its base OS (Debian buster) will soon (somewhere in 2024) be out of support.

We need to update to a more recent base image before that (or implement #239).

**Comment by kelson42** [comment]
I strongly suspect that we will have to implement #239 first, which will invalidate/fix this ticket as well.

**Comment by kelson42** [comment]
@benoit74 We will need to proceed here considering the conclusion of https://github.com/kiwix/container-images/issues/239
