### ISSUE TITLE
Make a script to check bad content-type HTTP header for all our mirrors

### ISSUE THREAD

**Issue by kelson42** [kiwix/container-images#73]
See #63... This should run one time a day and somehow the result should be monitored.

**Comment by kelson42** [comment]
We should also check like this is one of the mirror is unreachable.

**Comment by kelson42** [comment]
We also see the problem with the bad APK mime-type.

**Comment by kelson42** [comment]
We should look http://dante.ctan.org/mirmon/

**Comment by Rancho-rachit** [comment]
@kelson42 Where can I get list of mirrors for kiwix/zim ?

**Comment by rgaudin** [comment]
> @kelson42 Where can I get list of mirrors for kiwix/zim ?

https://download.kiwix.org/mirrors.html

Any file served my https://download.kiwix.org, you can add `?mirrorlist` to the URL and reveal all mirrors serving it. Eg: https://download.kiwix.org/mirrors.html?mirrorlist

**Comment by kelson42** [comment]
@rgaudin Can you please confirm this has been implemented?

**Comment by rgaudin** [comment]
Indeed
